security:
    enable_authenticator_manager: true
    
    # Configuration du hachage de mot de passe avec Argon2id
    password_hashers:
        App\Entity\User:
            algorithm: 'argon2id'
            memory_cost: 65536  # 64 MB
            time_cost: 4

    # Définition du provider d'utilisateurs
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern: ^/
            provider: entity_provider
            
            custom_authenticator:
                - App\Security\LoginFormAuthenticator
                
            logout:
                path: app_logout
                target: home
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_token
                csrf_token_id: logout
                
            # Configuration Remember Me sécurisée
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 1209600  # 14 jours
                secure: true
                samesite: 'lax'

    # Règles d'accès par URL
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/photographe, roles: ROLE_PHOTOGRAPHE }
        - { path: ^/superadmin, roles: ROLE_SUPERADMIN }
        - { path: ^/admin/planche, roles: ROLE_ADMIN }
        - { path: ^/admin/users, roles: ROLE_SUPERADMIN }
        
    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_PHOTOGRAPHE]
        ROLE_PHOTOGRAPHE: [ROLE_USER]
