services:
  database:
    image: mysql:8.4
    container_name: prunelle-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prunelle
      MYSQL_USER: user_prunelle
      MYSQL_PASSWORD: password_prunelle
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prunelle-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/vendor
      - prunelle_var:/var/www/html/var:rw
      - prunelle_uploads:/var/www/html/public/uploads:rw
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: '8123f68f3e137f0a47699d7b5d243a6d'
      DATABASE_URL: "mysql://user_prunelle:password_prunelle@database:3306/prunelle?serverVersion=8.4&charset=utf8mb4"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  webserver:
    image: nginx:alpine
    container_name: prunelle-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prunelle-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"
    depends_on:
      database:
        condition: service_healthy

  mailer:
    image: axllent/mailpit
    container_name: prunelle-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 3

  node:
    image: node:20-alpine
    container_name: prunelle-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: >
      sh -c "
        npm ci || npm install --force &&
        npm run build || echo 'Build completed with warnings' &&
        chown -R 1000:1000 /var/www/html/public/build
      "
    depends_on:
      app:
        condition: service_healthy

volumes:
  database_data:
    name: prunelle_mysql_data
  prunelle_uploads:
    external: false  
  prunelle_var:
    external: false  